[colors.bright]
black = "#565656"
blue = "#49a4f8"
cyan = "#99faf2"
green = "#c0e17d"
magenta = "#a47de9"
red = "#ec5357"
white = "#ffffff"
yellow = "#f9da6a"

[colors.normal]
black = "#2e2e2e"
blue = "#47a0f3"
cyan = "#64dbed"
green = "#abe047"
magenta = "#7b5cb0"
red = "#eb4129"
white = "#e5e9f0"
yellow = "#f6c744"

[colors.primary]
background = "#101421"
foreground = "#fffbf6"

[cursor.style]
blinking = "Never"
shape = "Block"

# [dpi]
# x = 144.0
# y = 144.0

[env]
TERM = "xterm-256color"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"


[font]
size = 20.0

[scrolling]
history = 10000

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "Hack Nerd Font Mono"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
key = "F11"

[keyboard.bindings.command]
args = ["-ir", "`xdotool getwindowfocus`", "-b", "toggle,fullscreen"]
program = "wmctrl"

[shell]
program = "/bin/bash"

[window]
decorations = "None"
dynamic_padding = true
dynamic_title = true
startup_mode = "Fullscreen"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 4
y = 2
